spring.application.name=experiment-7

spring.datasource.url=jdbc:h2:mem:experiment-7
spring.datasource.username=sa
spring.datasource.password=password
spring.datasource.driver-class-name=org.h2.Driver

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

jwt.secret=0dln6C4FpMH8wsfs4xd+MJ/YfTjHRrzyKje08rgma1A=
jwt.expiration=3600000
#openssl rand -base64 32